final File api = new File(basedir, 'target/class-diagrams/api.puml')
final File full = new File(basedir, 'target/class-diagrams/full.puml')
final File minimal = new File(basedir, 'target/class-diagrams/minimal.puml')
assert api.isFile()
assert full.isFile()
assert minimal.isFile()
final String apiText = api.getText('UTF-8')
final String fullText = full.getText('UTF-8')
final String minimalText = minimal.getText('UTF-8')
assert apiText.contains('Example()')
assert apiText.contains('exposed()')
assert !apiText.contains('Example(String)')
assert !apiText.contains('hidden()')
assert !apiText.contains('secret : String')
assert fullText.contains('Example()')
assert fullText.contains('Example(String)')
assert fullText.contains('exposed()')
assert fullText.contains('hidden()')
assert fullText.contains('secret : String')
assert minimalText.contains('Example')
assert !minimalText.contains('exposed()')
assert !minimalText.contains('secret : String')
